[package]
name = "ckb-notify"
version = "0.26.1-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-logger = { path = "../util/logger" }
ckb-types = { path = "../util/types" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
ckb-stop-handler = { path = "../util/stop-handler" }
crossbeam-channel = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
